name: build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Build package
    permissions:
      # This permission is needed for private repositories.
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.9.8" # uv version
        python-version: "3.12"

    #- name: Install Hatch and uv-dynamic-versioning
    #  # for dynamic version resolution from git tag
    #  # we also need to explicitly create a venv here
    #  run: |
    #    uv venv
    #    uv pip install hatch uv-dynamic-versioning
    
    - name: Install the project
      run: uv sync --locked --all-extras --dev --inexact
    
    - name: Build package
      run: uv build
